source(file.path("R", "utils.R"))
project_dir <- client_root
work_dir <- file.path(project_dir, "work", "03_cluster_markers_enrichment")
result_dir <- file.path(project_dir, "results", "03_Subcluster_Markers_Enrichment")
log_dir <- file.path(project_dir, "logs")
dir.create(work_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(result_dir, recursive = TRUE, showWarnings = FALSE)
unlink(list.files(result_dir, full.names = TRUE), recursive = TRUE, force = TRUE)
scRNA <- readRDS(file.path(project_dir, "work", "02_scRNA_annotation_abundance", "scRNA_annotated.rds"))
ClusterGVis_module(object = scRNA, OutPath = work_dir, scRNA.markers = NULL, celltype = "cellType_1", species = NA, OnlyPlot = FALSE)
pdfs <- list.files(work_dir, pattern = "\\.pdf$", recursive = TRUE, full.names = TRUE)
stopifnot(length(pdfs) > 0)
for (f in pdfs) stopifnot(file.copy(f, file.path(result_dir, basename(f)), overwrite = TRUE))
stopifnot(all(tolower(tools::file_ext(list.files(result_dir))) == "pdf"))
capture.output(sessionInfo(), file = file.path(log_dir, "03_cluster_markers_enrichment_sessionInfo.txt"))
