source(file.path("R", "utils.R"))
project_dir <- client_root
work_dir <- file.path(project_dir, "work", "04_scBPS_key_cell")
result_dir <- file.path(project_dir, "results", "04_scBPS_Key_Cell")
log_dir <- file.path(project_dir, "logs")
dir.create(work_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(result_dir, recursive = TRUE, showWarnings = FALSE)
unlink(list.files(result_dir, full.names = TRUE), recursive = TRUE, force = TRUE)
scRNA <- readRDS(file.path(project_dir, "work", "02_scRNA_annotation_abundance", "scRNA_annotated.rds"))
run_scBPS_pipeline(scrna_obj = scRNA, celltype_col = "cellType_1", gwas = "Dutch207", output_dir = work_dir, Only_Plot = FALSE)
pdfs <- list.files(work_dir, pattern = "\\.pdf$", recursive = TRUE, full.names = TRUE)
stopifnot(length(pdfs) == 4)
for (f in pdfs) stopifnot(file.copy(f, file.path(result_dir, basename(f)), overwrite = TRUE))
stopifnot(all(tolower(tools::file_ext(list.files(result_dir))) == "pdf"))
capture.output(sessionInfo(), file = file.path(log_dir, "04_scBPS_key_cell_sessionInfo.txt"))
